version: '3'

services:
  traefik:
    image: traefik:latest
    hostname: traefik
    container_name: traefik
    command:
      - '--docker.domain=${PROJECT_DOMAIN}'
      - '--logLevel=${TRAEFIK_LOG_LEVEL}'
    networks:
      - proxy
      - monitor-net
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.${PROJECT_DOMAIN}`)'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - monitor-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${PROJECT_DOMAIN}`)'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
    restart: unless-stopped

  prom_node_exporter:
    image: prom/node-exporter
    hostname: prom-node-exporter
    container_name: prom-node-exporter
    networks:
      - monitor-net
    labels:
      - 'traefik.enable=false'
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor:latest
    hostname: cadvisor
    container_name: cadvisor
    networks:
      - monitor-net
    volumes:
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    labels:
      - 'traefik.enable=false'
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - monitor-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${PROJECT_DOMAIN}`)'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitor-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.${PROJECT_DOMAIN}`)'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local
  portainer_data:
    driver: local

networks:
  proxy:
  monitor-net:
